<?xml version="1.0" encoding="UTF-8" ?>
<ThisIsNotT3DataStructure>
    <sheets>
        <sDEF>
            <ROOT>
                <type>array</type>
                <el>
                    <foo>
                        <config>
                            <type>select</type>
                            <maxitems>1</maxitems>
                        </config>
                    </foo>
                </el>
            </ROOT>
        </sDEF>
    </sheets>
</ThisIsNotT3DataStructure>
